In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

In [2]:
# Creando un array bidimensional.

bidimensional = np.random.rand(5, 4)
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

El array bidimensional que tenemos es: 
 [[0.34009705 0.40411859 0.49843368 0.45504266]
 [0.91761256 0.29115295 0.4986929  0.84734358]
 [0.691421   0.52717712 0.62187678 0.59264184]
 [0.30485091 0.08664154 0.56170624 0.95638368]
 [0.00376363 0.99193103 0.86146804 0.78641231]]


In [3]:
# antes de seguir vamos a aprender el método np.round(), que al igual que en Python básico nos permite redondear los valores de los elementos de nuestor array

bidimensional_red = np.round(bidimensional, 2)

# donde el primer argumento es el elemento que queremos tratar (en este caso nuestro array bidimensional, y el segundo la cantida de decimales, en nuestro caso 2)

bidimensional_red

array([[0.34, 0.4 , 0.5 , 0.46],
       [0.92, 0.29, 0.5 , 0.85],
       [0.69, 0.53, 0.62, 0.59],
       [0.3 , 0.09, 0.56, 0.96],
       [0.  , 0.99, 0.86, 0.79]])

Ya estamos en condiciones de aplicar algunos calculos estadisticos a mi array, en este caso podriamos calcular la media DE TODO MI ARRAY simplemente aplicando el metodo np.mean() al array donde quiero aplicar esta funcion.

In [4]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la media de todos los elementos del array

media = np.mean(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la media de todos los elementos del array es: \n {media}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El cálculo de la media de todos los elementos del array es: 
 0.562


Anteriormente vimos que podiamos aplicar np.mean() a todo mi array, aunque podria suceder el caso de que quisieramos aplicarlo a las columnas, por lo tanto con lo que vimos en el ejermplo atenrior, solo debemos agregar el eje al que vamos a aplicar este calculo, como son las columnas mi eje sera 0 (cero), la sintaxis la vemos en el ejemplo como axis=0.

In [5]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la media por cada COLUMNA que tenemos en el array

media_col = np.mean(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La media de cada COLUMNA (axis = 0) del array es: \n {media_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La media de cada COLUMNA (axis = 0) del array es: 
 [0.45  0.46  0.608 0.73 ]


Si podemos calcular la media de cada columna, entonces tambien podremos hacer lo mismo con cada fila, cambiando el valor del eje de 0 al valor de 1, es decir que la sintaxis ser axis=1.

In [6]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la media por cada FILA que tenemos en el array

media_fila = np.mean(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La media de cada FILA (axis = 1) del array es: \n {media_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La media de cada FILA (axis = 1) del array es: 
 [0.425  0.64   0.6075 0.4775 0.66  ]


### `np.var()`

Calcula la varianza de los valores de mi *array*. Por defecto lo hará sobre todo el *array*, pero nosotros le podemos especificar el eje usando el parámetro `axis`. La **varianza** es una medida estadística que indica qué tan dispersos están los valores de un conjunto de datos alrededor de su media. Es una medida de la variabilidad de los datos. Una varianza alta indica que los valores están más dispersos, mientras que una varianza baja indica que los valores están más cercanos a la media.

- `axis = 0`: columnas
- `axis = 1`: filas



In [7]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la varianza de todos los elementos de array

varianza = np.var(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la varianza de todos los elementos del array es: \n {varianza}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El cálculo de la varianza de todos los elementos del array es: 
 0.074496


In [8]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la varianza por cada COLUMNA que tenemos en el array

varianza_col = np.var(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La varianza de cada COLUMNA (axis = 0) del array es: \n {varianza_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La varianza de cada COLUMNA (axis = 0) del array es: 
 [0.10312  0.09104  0.017856 0.03268 ]


In [10]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la varianza por cada FILA que tenemos en el array

varianza_fila = np.var(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La varianza de cada FILA (axis = 1) del array es: \n {varianza_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La varianza de cada FILA (axis = 1) del array es: 
 [0.003675   0.06615    0.00331875 0.10531875 0.15035   ]


### `np.std()`

Calcula la desviación estándar en nuestro *array*, como hasta ahora, por defecto nos lo va a calcular para todos los elementos. La **desviación estándar** es una medida estadística que indica cuánto varían los valores de un conjunto de datos con respecto a la media. Proporciona una medida de dispersión o variabilidad en los datos. Una desviación estándar alta indica que los valores del conjunto de datos están más dispersos, mientras que una desviación estándar baja indica que los valores están más cerca de la media.


Entonces... ¿Cuál es la diferencia entre desviación y varianza?

- La varianza mide la dispersión de los datos alrededor de la media, expresada en unidades al cuadrado.
- La desviación estándar mide la dispersión de los datos alrededor de la media, expresada en las mismas unidades que los datos originales.

Si le pasamos el parámetro `axis` podemos especificar sobre que eje queremos que nos calcule la desviación estándar. 

- `axis = 0`: columnas
- `axis = 1`: filas

In [11]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la desviación de todos los elementos de array

desviación = np.std(bidimensional_red)
print("--------------------------")
print(f"El cálculo de la desviacion de todos los elementos del array es: \n {desviación}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El cálculo de la desviacion de todos los elementos del array es: 
 0.2729395537477117


In [12]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la desviación por cada COLUMNA que tenemos en el array

desviacion_col = np.std(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La desviación de cada COLUMNA (axis = 0) del array es: \n {desviacion_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La desviación de cada COLUMNA (axis = 0) del array es: 
 [0.32112303 0.30172835 0.13362634 0.1807761 ]


In [13]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la desviación por cada FILA que tenemos en el array

desviacion_fila = np.std(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La desviación de cada FILA (axis = 1) del array es: \n {desviacion_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La desviación de cada FILA (axis = 1) del array es: 
 [0.06062178 0.25719642 0.05760859 0.3245285  0.38774992]


## Operaciones aritméticas

### `np.min()`

Nos devuelve el valor mínimo de nuestro *array*. 

De la misma forma que `np.mean()` nos va a permitir identificar los valores mínimos a través de las columnas o las filas usando el parámetro `axis`. 

Igual que en `np.mean()`:

- `axis = 0`: columnas
- `axis = 1`: filas

In [14]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# sacamos el valor mínimo del array

minimo = np.min(bidimensional_red)
print("--------------------------")
print(f"El valor mínimo de todos los elementos del array es: \n {minimo}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor mínimo de todos los elementos del array es: 
 0.0


In [15]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# sacamos el valor mínimo de cada COLUMNA que tenemos en el array

minimo_col = np.min(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"El valor mínimo de cada COLUMNA (axis = 0) del array es: \n {minimo_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor mínimo de cada COLUMNA (axis = 0) del array es: 
 [0.   0.09 0.5  0.46]


In [16]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# sacamos el valor mínimo de cada FILA que tenemos en el array

minimo_fila = np.min(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"El valor mínimo de cada FILA (axis = 1) del array es: \n {minimo_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor mínimo de cada FILA (axis = 1) del array es: 
 [0.34 0.29 0.53 0.09 0.  ]


### `np.max()`

Nos devuelve el valor máximo de nuestro *array*. 

Podemos seguir trabajando con el parámetro `axis` para sacar los valores máximos por filas o columnas:

- `axis = 0`: columnas
- `axis = 1`: filas

In [17]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos el valor máximo de todos los elementos del array
maximo = np.max(bidimensional_red)
print("--------------------------")
print(f"El valor máximo de todos los elementos del array es: \n {maximo}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor máximo de todos los elementos del array es: 
 0.99


In [18]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos el valor máximo por cada COLUMNA que tenemos en el array

maximo_col = np.max(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"El valor máximo de cada COLUMNA (axis = 0) del array es: \n {maximo_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor máximo de cada COLUMNA (axis = 0) del array es: 
 [0.92 0.99 0.86 0.96]


In [19]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos el valor máximo por cada FILA que tenemos en el array

maximo_fila = np.max(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"El valor máximo de cada FILA (axis = 1) del array es: \n {maximo_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
El valor máximo de cada FILA (axis = 1) del array es: 
 [0.5  0.92 0.69 0.96 0.99]


### `np.sum()`

Suma los elementos del *array*. Por defecto nos va a sumar todos los elementos del *array* (nos devuelve un único valor). Podemos especificar que nos haga la suma por filas o columnas con el parámetro `axis` (nos devolverá un valor por cada fila o columna que tengamos):

- `axis = 0`: columnas
- `axis = 1`: filas

In [20]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la suma de todos los elementos de array

suma = np.sum(bidimensional_red)
print("--------------------------")
print(f"La suma de todos los elementos del array es: \n {suma}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La suma de todos los elementos del array es: 
 11.240000000000002


In [21]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la suma de todos los elementos por cada COLUMNA que tenemos en el array

suma_col = np.sum(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La suma de los elementos de cada COLUMNA (axis = 0) del array es: \n {suma_col}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La suma de los elementos de cada COLUMNA (axis = 0) del array es: 
 [2.25 2.3  3.04 3.65]


In [22]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# calculamos la suma de todos los elementos por cada FILA que tenemos en el array

suma_fila = np.sum(bidimensional_red, axis = 1) # noten que agregamos un eje donde aplico la funcion
print("--------------------------")
print(f"La suma de los elementos de cada FILA (axis = 1) del array es: \n {suma_fila}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------
La suma de los elementos de cada FILA (axis = 1) del array es: 
 [1.7  2.56 2.43 1.91 2.64]


## Otros métodos

### `np.sort()`

Devuelve una copia ordenada de un *array*.

Por defecto nos ordenará por filas de nuestro *array*, si lo que queremos es que nos ordene por columnas tendremos que pasarle el parámetro `axis = 0`. 

In [23]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# ordenamos el array con el método np.sort()

bidimensional_red_ordenado_filas = np.sort(bidimensional_red) #por defecto esta en axis=1 y no haria falta especificarlo.
print("--------------------------\n")
print("El array ordenado por CADA FILA de menor a mayor es: \n", bidimensional_red_ordenado_filas)


El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------

El array ordenado por CADA FILA de menor a mayor es: 
 [[0.34 0.4  0.46 0.5 ]
 [0.29 0.5  0.85 0.92]
 [0.53 0.59 0.62 0.69]
 [0.09 0.3  0.56 0.96]
 [0.   0.79 0.86 0.99]]


Si nos fijamos, el *array* esta ordenado de menor a mayor en cada fila. Si quisieramos ordenarlo de menor a mayor por columnas tendremos que usar el parámetro `axis = 0`

In [24]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# ordenamos el array con el método np.sort()

bidimensional_red_ordenado_col = np.sort(bidimensional_red, axis = 0) # noten que agregamos un eje donde aplico la funcion
print("--------------------------\n")
print("El array ordenado por CADA COLUMNA de menor a mayor es: \n", bidimensional_red_ordenado_col)

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------

El array ordenado por CADA COLUMNA de menor a mayor es: 
 [[0.   0.09 0.5  0.46]
 [0.3  0.29 0.5  0.59]
 [0.34 0.4  0.56 0.79]
 [0.69 0.53 0.62 0.85]
 [0.92 0.99 0.86 0.96]]


⚠️ Si nos fijamos en cualquiera de los casos nos esta ordenando de menor a mayor. 

Pero... ¿Qué pasaría si quisieramos ordenar de mayor a menor? 

Le tendríamos que dar la vuelta primero al *array* y luego ordenarlo. ¿Cómo podemos darle la vuelta a un *array*? 

> Utilizando el operador `-` delante del *array* y del método


In [25]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# le ponemos un símbolo '-' al array, fijaos que lo ponemos todos los elementos a negativos

print("--------------------------\n")
print(f"El array con un símbolo '-' antes es: \n {-bidimensional_red}")

# ahora vamos a ordenar este array con el método np.sort()

print("--------------------------\n")
print(f"El array con un símbolo '-' antes y usando el método 'np.sort()' es: \n {np.sort(-bidimensional_red)}")

# si nos fijamos ahora, si ignoramos los símbolos '-' los valores más altos están al inicio de las filas, por lo que
# tendremos que hacer ahora es quitarle los símbolos '-'. Para eso lo que haremos será poner un símbolo '-' delante del 'np.sort()'

print("--------------------------\n")
print(f"El array con un símbolo '-' antes y usando el método 'np.sort()' y volviendolo a poner en negativo es: \n {-np.sort(-bidimensional_red)}")

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------

El array con un símbolo '-' antes es: 
 [[-0.34 -0.4  -0.5  -0.46]
 [-0.92 -0.29 -0.5  -0.85]
 [-0.69 -0.53 -0.62 -0.59]
 [-0.3  -0.09 -0.56 -0.96]
 [-0.   -0.99 -0.86 -0.79]]
--------------------------

El array con un símbolo '-' antes y usando el método 'np.sort()' es: 
 [[-0.5  -0.46 -0.4  -0.34]
 [-0.92 -0.85 -0.5  -0.29]
 [-0.69 -0.62 -0.59 -0.53]
 [-0.96 -0.56 -0.3  -0.09]
 [-0.99 -0.86 -0.79 -0.  ]]
--------------------------

El array con un símbolo '-' antes y usando el método 'np.sort()' y volviendolo a poner en negativo es: 
 [[0.5  0.46 0.4  0.34]
 [0.92 0.85 0.5  0.29]
 [0.69 0.62 0.59 0.53]
 [0.96 0.56 0.3  0.09]
 [0.99 0.86 0.79 0.  ]]


### `np.transpose()`

Es una función de la biblioteca NumPy que se utiliza para intercambiar las dimensiones de un *array*. Toma como argumento un *array* y devuelve un nuevo *array* con las dimensiones intercambiadas.

La sintaxis básica de `np.transpose` es la siguiente:

```python
np.transpose(arr, axes)
```

Donde:
- `arr`: Es la matriz que deseas transponer.
- `axes`: Es una tupla opcional que especifica cómo se deben reordenar las dimensiones. Cada elemento de la tupla representa la dimensión correspondiente en la matriz transpuesta. Si no se proporciona `axes`, se realiza una permutación de las dimensiones en orden inverso.

Visualmente lo podemos ver así:


![image-2.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/transpose.png?raw=true)


En resumen, `np.transpose` es una función útil para cambiar las dimensiones de una matriz en NumPy. Puede ser especialmente útil en el análisis de datos cuando se necesita cambiar el orden de filas y columnas para realizar cálculos o manipulaciones específicas.


Veamos varios ejemplos con arrays de distintas dimensiones:

#### Unidimensional

No tiene mucho sentido hacer una transposición de un *array* de una dimensión ya que:

> La transposición de un *array* unidimensional devuelve una vista inalterada del *array* original.

#### Bidimensional

Va ha cambiar las filas por columnas en nuestro *array*

In [27]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {bidimensional_red}")

# transponemos el array bidimensional usando el método'np.transpose()'
# Fijaos como después de aplicar el método transpose tenemos 4 filas y 5 columnas. El array original tenia 5 filas  y 4 columnas

print("--------------------------\n")
bidimensional_red_trans = np.transpose(bidimensional_red)
print(f"El array después de aplicar el método 'np.transpose()': \n {bidimensional_red_trans}")


El array con el que vamos a trabajar en este apartado de la lección es: 
 [[0.34 0.4  0.5  0.46]
 [0.92 0.29 0.5  0.85]
 [0.69 0.53 0.62 0.59]
 [0.3  0.09 0.56 0.96]
 [0.   0.99 0.86 0.79]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[0.34 0.92 0.69 0.3  0.  ]
 [0.4  0.29 0.53 0.09 0.99]
 [0.5  0.5  0.62 0.56 0.86]
 [0.46 0.85 0.59 0.96 0.79]]


#### Multidimensional

La cosa se complica cuando pasamos a *arrays* con más de dos dimensiones. 

Por defecto este método nos hará la siguiente transposicion:

- El número de columnas --> número de *arrays* 


- El número de filas --> número de filas


- El número de *arrays* --> número de columnas

In [30]:
# creando mi array de 3D

lista_listas_listas = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]
tridimensional = np.array(lista_listas_listas)

print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {tridimensional}")

# aplicamos el método 'np.transpose()' para ver que nos devuelve por defecto
print("--------------------------\n")


tridimensional_trans_defecto = np.transpose(tridimensional)
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_defecto}")

# antes teníamos un array de 2 matrices x 2 filas x 5 columnas
# después tenemos un array de 5 matrices x 2  filas x 2 columnas

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[[ 1 11]
  [ 6 16]]

 [[ 2 12]
  [ 7 17]]

 [[ 3 13]
  [ 8 18]]

 [[ 4 14]
  [ 9 19]]

 [[ 5 15]
  [10 20]]]


Pero nosotras podemos especificar el sentido en el que queremos que transpongan los elementos de mi *array*

```python
np.transpose(nuestro_array, (1,2,0))
```

Entendiendo lo siguiente cuando definimos el siguiente *array*:

```python
multidimensional = np.random.randint(0,100, (2,3,5))
```

- 2 (posición 0): hace referencia a el número de *subarrays* o  matrices que queremos. 


- 3 (posición 1): hace referencia al número de filas que queremos en cada uno de nuestros *subarrays*.


- 5 (posición 2): hace referencia al número de columnas que queremos en cada uno de nuestros *subarrays*. 

> A este método le podemos pasar un parámetro adicional que puede ser una tupla o una lista donde indicaremos el orden de permutación que queremos

**¿Cómo lo hacemos?**

Lo haremos indicando donde queremos cada una de las posiciones antiguas. Es decir, imaginemos que queremos hacer la siguiente transposición:

- Las columnas (posición 2) queremos que sean las filas (posición 1)


- Las filas (posición 1) queremos que sean el número de *arrays* (posición 0)


- El número de *arrays* (posición 0) queremos que sean columnas (posición 2)

Lo único que tendremos que hacer es especificar este nuevo orden en el `transpose()`

```python
np.transpose(multidimensional, (1,2,0))
```

Si nos fijamos lo que hacemos en la tupla es, basándonos en las posiciones de la tupla:

- ¿Qué quiero en la posición 0 de la tupla (y por lo tanto de mi nuevo *array* transpuesto*? -- > lo que antes era la posición 1. Por lo tanto, pongo un 1


- ¿Qué quiero en la posción 1? --> lo que antes era la posición 2. Por lo tanto, pongo un 2



- ¿Qué quiero en la posición 2? --> lo que antes era la posición 0. Por lo tanto, pongo un 0

In [29]:
print(f"El array con el que vamos a trabajar en este apartado de la lección es: \n {tridimensional}")

# aplicamos el método 'np.transpose()' para ver que nos devuelve por defecto

print("--------------------------\n")
tridimensional_trans_1 = np.transpose(tridimensional, (1,2,0))
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_1}")

# antes teníamos un array de 2 matrices x 2 filas x 5 columnas
# después tenemos un array de 2 matrices x 5 filas x 2 columnas

El array con el que vamos a trabajar en este apartado de la lección es: 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
--------------------------

El array después de aplicar el método 'np.transpose()': 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


## `reshape()`:

`np.reshape` es una función de NumPy que se utiliza para cambiar la forma de un *array* sin cambiar sus datos subyacentes. Permite reorganizar los elementos de un *array* en una nueva forma especificada por el usuario.

La sintaxis básica de `np.reshape` es la siguiente:

```python
np.reshape(a, newshape, order='C')
```

Donde:
- `a`: Es la matriz que se desea remodelar.
- `newshape`: Es la nueva forma deseada de la matriz, especificada como una tupla de enteros.
- `order` (opciona): Especifica el orden en el que se deben leer los elementos de la matriz. Puede tomar dos valores: 'C' (por defecto) para leer los elementos en orden de fila (por filas) y 'F' para leer los elementos en orden de columna (por columnas).

In [31]:
# definimos un array unidimensional utilizando el método 'np.array()'

a = np.array([1, 2, 3, 4, 5, 6])
print(f"El array con el que vamos a trabajar es: \n {a}")

# Si queremos remodelar esta matriz en una matriz bidimensional 
# de 2 filas y 3 columnas, podemos usar `np.reshape` de la siguiente manera:

print("\n--------------------------\n")
reshaped_a = np.reshape(a, (2, 3))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_a}")


El array con el que vamos a trabajar es: 
 [1 2 3 4 5 6]

--------------------------

El array después de aplicar el método 'np.reshape()' es: 
 [[1 2 3]
 [4 5 6]]



También podemos utilizar `np.reshape` para remodelar *arrays* multidimensionales. Veamos un ejemplo:

In [32]:
# definimos un array unidimensional utilizando el método 'np.array()'

b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"El array con el que vamos a trabajar es: \n {b}")

# Si queremos remodelar esta matriz en una matriz bidimensional 
# de 2 filas y 3 columnas, podemos usar `np.reshape` de la siguiente manera:

print("\n--------------------------\n")
reshaped_b = np.reshape(a, (6,))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_b}")

El array con el que vamos a trabajar es: 
 [[1 2 3]
 [4 5 6]]

--------------------------

El array después de aplicar el método 'np.reshape()' es: 
 [1 2 3 4 5 6]


## `np.swapaxes()`

El método `np.swapaxes` se utiliza para intercambiar dos ejes (dimensiones) específicos de un *array*. Permite reorganizar los ejes de un *array* sin cambiar los datos subyacentes.

La sintaxis básica de `np.swapaxes` es la siguiente:

```python
np.swapaxes(arr, axis1, axis2)
```

Donde:
- `arr` es la matriz en la que se desea intercambiar los ejes.
- `axis1` y `axis2` son los ejes que se deben intercambiar.

In [37]:
# definimos un array nuevo bidimensional

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"El array con el que vamos a trabajar es: \n {arr}")

# Si queremos intercambiar los ejes de este array, podemos usar `np.swapaxes` de la siguiente manera:

print("\n--------------------------\n")
swapped_arr = np.swapaxes(arr, 0, 1)
print(f"El array después de aplicar el método 'np.swapaxes()' es:\n {swapped_arr}")

El array con el que vamos a trabajar es: 
 [[1 2 3]
 [4 5 6]]

--------------------------

El array después de aplicar el método 'np.swapaxes()' es:
 [[1 4]
 [2 5]
 [3 6]]


In [34]:
# definimos un array nuevo tridimensional

arr_3d = np.array([[[1, 2, 3], [3, 4, 3]], [[5, 6, 4], [7, 8, 4]]])
print(f"El array con el que vamos a trabajar es: \n {arr_3d}")

# Si queremos intercambiar los ejes 0 (matrices) y 2 (columnas) de este array, podemos hacer lo siguiente:

print("\n--------------------------\n")
swapped_arr_3d = np.swapaxes(arr_3d, 0, 2)
print(f"El array después de aplicar el método 'np.swapaxes()' es: \n {swapped_arr_3d}")

El array con el que vamos a trabajar es: 
 [[[1 2 3]
  [3 4 3]]

 [[5 6 4]
  [7 8 4]]]

--------------------------

El array después de aplicar el método 'np.swapaxes()' es: 
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]

 [[3 4]
  [3 4]]]


En este caso, el eje 0 representaba las matrices individuales, el eje 1 representaba las filas y el eje 2 representaba las columnas. Después del intercambio, el eje 0 representa las columnas, el eje 1 representa las filas y el eje 2 representa las matrices individuales.


## `np.copy()`

El método `np.copy()` en NumPy se utiliza para realizar una copia completa de un array NumPy, incluyendo sus datos y su estructura. Esto significa que se crea una nueva instancia del array con los mismos datos que el array original, pero completamente independiente de él. 

La copia no comparte ninguna referencia de memoria con el array original, lo que significa que cualquier modificación hecha en la copia no afectará al array original, y viceversa.

In [35]:
#creamos un array para el ejemplo, puede ser de cualquier dimension y forma

original_array = np.array([1, 2, 3, 4, 5])

# Creamos una copia del array

copia_array = original_array.copy()

# Modificamos la copia

copia_array[0] = 100

# Imprimimos ambos arrays

print("Array original:", original_array)
print("--------------------------")
print("Copia modificada:", copia_array)

Array original: [1 2 3 4 5]
--------------------------
Copia modificada: [100   2   3   4   5]


## `np.flatten()`

El método `np.flatten()` en NumPy es una función que se utiliza para convertir un array multidimensional en un array unidimensional, es decir, aplana el array. Esto significa que toma todos los elementos del array, independientemente de su forma original (dimensionalidad), y los coloca en una sola dimensión.

La principal utilidad de flatten() radica en simplificar la manipulación y el procesamiento de datos cuando se trabaja con arrays multidimensionales. Al convertir un array multidimensional en un array unidimensional, se puede acceder a todos los elementos de manera secuencial, lo que facilita su procesamiento mediante operaciones de iteración, filtrado, ordenamiento u otras manipulaciones de datos.

In [36]:
# Crear un array multidimensional

array_multidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array multidimensional original:")
print(array_multidimensional)
print()

# Aplicar flatten() para convertirlo en un array unidimensional

array_unidimensional = array_multidimensional.flatten()

print("Array unidimensional obtenido con flatten():")
print(array_unidimensional)

Array multidimensional original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array unidimensional obtenido con flatten():
[1 2 3 4 5 6 7 8 9]
