## Indexación en *arrays* unidimensionales

La indexación se utiliza para acceder y manipular elementos individuales o grupos de elementos en un array. En NumPy, la indexación se realiza utilizando corchetes `[]`, al igual que hacíamos en listas. 

```python
array[i]
# donde i es el índice del elemento al que queremos acceder
```


In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

In [2]:
# Imaginemos que tenemos el siguiente array unidimensional con 15 elementos
## en nuestro array

unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos acceder al primer elemento de nuestro array

print("\n---------------------------\n")
print(f"El primer elemento de nuestro array es: \n {unidimensional[0]}")

El array unidimensional que tenemos es: 
 [0.67575488 0.28182152 0.65515444 0.20632512 0.71131779 0.20960919
 0.4886184  0.26038713 0.10262921 0.5356864  0.26646291 0.70740141
 0.72475719 0.76623537 0.17789398]

---------------------------

El primer elemento de nuestro array es: 
 0.675754882687407


Bien! en caso de querer obtener o acceder a los ultimos 3 elementos podriamos hacerlo de la misma forma que haciamos con las listas.

In [3]:
# Creando un array de 15 elementos para usarse de ejemplo

unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")


# Si queremos acceder a los tres últimos elementos:

print("\n---------------------------\n")
print(f"Los tres últimos elementos de nuestro array son: \n {unidimensional[-3:]}")

El array unidimensional que tenemos es: 
 [0.91696331 0.4149689  0.66907725 0.63214377 0.26827108 0.71007883
 0.18876391 0.53444146 0.37434589 0.89930637 0.57548693 0.46502241
 0.71862079 0.96563361 0.12117375]

---------------------------

Los tres últimos elementos de nuestro array son: 
 [0.71862079 0.96563361 0.12117375]


Para una seleccion acotada de elementos, nuevamente lo hacemos de manera similiar que las listas, esta vez para los elementos ubicados desde la posicion 2 (incluido) y la posicion 4 (no incluido), MUCHA ATENCION EN COMO SE SELECCIONAN LOS ELEMENTOS!!

In [4]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos seleccionar el tercer y cuarto elemento:

print("\n---------------------------\n")
print(f"El tercer y cuarto elemento de nuestro array son: \n {unidimensional[2:4]}")


El array unidimensional que tenemos es: 
 [0.45058823 0.38865985 0.28394189 0.55751163 0.49542263 0.06076812
 0.67575991 0.53378958 0.6450878  0.35035437 0.30631852 0.48827426
 0.42771376 0.52168097 0.27600968]

---------------------------

El tercer y cuarto elemento de nuestro array son: 
 [0.28394189 0.55751163]


Al continuar con la selección de elementos, observamos que podemos realizar una seleccion mas acotada, es decir desde una posicion inicial a una posicion final. Ahora supongamos que se nos solicita seleccionar todos los elementos desde el inicio hasta la posición 10. Es importante recordar que, dado que deseamos incluir la posición 10, debemos indicar como límite el 11, lo que se representará de la siguiente manera: [:11]. Además, los elementos que deben ser seleccionados iran en saltos de dos posiciones. Por lo tanto, la expresión completa será [:11:2], no olvides la regla de "start:stop:step".

In [6]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# los elementos desde el inicio hasta el 10 en saltos de dos en dos

print("\n---------------------------\n")
print(f"Los elementos desde el inicio hasta el 10 de dos en dos son: \n {unidimensional[:11:2]}")

El array unidimensional que tenemos es: 
 [0.16354721 0.20891221 0.38105538 0.61679731 0.61399683 0.04807515
 0.6933412  0.27507816 0.21595989 0.11239948 0.26234806 0.37746188
 0.21131478 0.61224184 0.47302522]

---------------------------

Los elementos desde el inicio hasta el 10 de dos en dos son: 
 [0.16354721 0.38105538 0.61399683 0.6933412  0.21595989 0.26234806]


## Indexación en *arrays* bidimensionales

En el caso de este tipo de *arrays*, se puede acceder a elementos individuales en una matriz bidimensional utilizando la sintaxis `[fila, columna]` entre corchetes.

Los podemos entender como una lista de listas.

```python
array[i,j]
array[i][j]

# 🚨 Las dos lineas anteriores son exactamente lo mismo
# seleccionará el elemento de la fila "i" y columna "j"
```


Donde: 
- `i` --> filas

- `j` --> columnas

In [7]:
# definimos un array bidimensional
# en este caso estamos generando un array de 5 filas y 4 columnas con números aleatorios entre el 0 y el 1

bidimensional = np.random.rand(5, 4)
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# desgranemos la indexación en este tipo de arrays
# si accedemos al elemento 0 del array obtenemos a la fila que queramos de nuestro array

print(f"\nEl primer elemento de nuestro array es: \n {bidimensional[0]}")

El array bidimensional que tenemos es: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]
 [0.30681968 0.97389609 0.35959673 0.77068683]
 [0.96928977 0.53593699 0.47855086 0.90309008]
 [0.91165536 0.27855109 0.02903459 0.12396901]]

El primer elemento de nuestro array es: 
 [0.25275001 0.56706732 0.65262712 0.06680611]


In [8]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# dado el resultado del paso anterior, sigamos buceando en el array, 
# en este caso querremos acceder al primer elemento del resultado anterior
# fijaos como ponemos dos indices, el primero para acceder a las filas 
# y el segundo para acceder a las columnas
# podríamos decir que es como el juego de hundir la flota

print(f"\nEl primer elemento de la primera fila de nuestro array es: \n {bidimensional[0][0]}")
print("\n-------------------------------------\n")
print(f"bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: \n {bidimensional[0,0]}")

El array bidimensional que tenemos es: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]
 [0.30681968 0.97389609 0.35959673 0.77068683]
 [0.96928977 0.53593699 0.47855086 0.90309008]
 [0.91165536 0.27855109 0.02903459 0.12396901]]

El primer elemento de la primera fila de nuestro array es: 
 0.2527500069408498

-------------------------------------

bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: 
 0.2527500069408498


In [9]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# accedemos a la segunda fila, tercer columna. 

print("\n---------------------------\n")
print(f"El elemento que esta en la 2ª fila y 3ª columna es: \n {bidimensional[1,2]}")


El array bidimensional que tenemos es: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]
 [0.30681968 0.97389609 0.35959673 0.77068683]
 [0.96928977 0.53593699 0.47855086 0.90309008]
 [0.91165536 0.27855109 0.02903459 0.12396901]]

---------------------------

El elemento que esta en la 2ª fila y 3ª columna es: 
 0.5190254082531592


📌 **NOTA** Cuando usamos la siguiente estructura `array[i,j]`: 

- Todo lo que haya antes de la coma se referirá a filas.


- Todo lo que haya después de la coma se referirá a columnas. 

De esta forma, si por ejemplo queremos seleccionar solo las dos primeras filas usaremos la nomenclatura que ya conocemos con los `:`. Si no especificamos nada (o solo ponemos `:`) se entiende que lo queremos todo. Por ejemplo 👇🏽

In [10]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# seleccionamos las dos primeras filas, y todas las columnas (no ponemos 
# nada después de la coma). 

print("\n---------------------------\n")
print(f"Las dos primeras filas con todas sus columnas son: \n {bidimensional[:2,:]}")


El array bidimensional que tenemos es: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]
 [0.30681968 0.97389609 0.35959673 0.77068683]
 [0.96928977 0.53593699 0.47855086 0.90309008]
 [0.91165536 0.27855109 0.02903459 0.12396901]]

---------------------------

Las dos primeras filas con todas sus columnas son: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]]


In [11]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# seleccionamos todas las filas y solo las tres últimas columnas

print("\n---------------------------\n")
print(f"Todas las filas y las últimas tres columnas son: \n {bidimensional[:,-3:]}")

El array bidimensional que tenemos es: 
 [[0.25275001 0.56706732 0.65262712 0.06680611]
 [0.99842895 0.45933483 0.51902541 0.12679932]
 [0.30681968 0.97389609 0.35959673 0.77068683]
 [0.96928977 0.53593699 0.47855086 0.90309008]
 [0.91165536 0.27855109 0.02903459 0.12396901]]

---------------------------

Todas las filas y las últimas tres columnas son: 
 [[0.56706732 0.65262712 0.06680611]
 [0.45933483 0.51902541 0.12679932]
 [0.97389609 0.35959673 0.77068683]
 [0.53593699 0.47855086 0.90309008]
 [0.27855109 0.02903459 0.12396901]]


## Indexación en *arrays* tridimensionales

De la misma forma que en los bidimensionales, el los mutidimensionales podemos acceder a sus elementos de dos formas: 

```python
array[i,j,k]
array[i][j][k]
```

- i → *array* al que queremos acceder 


- j → fila de nuestro *array* al que queremos acceder


- k → columna de nuestro *array* al que queremos acceder

    ![3d-array-index.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/index_numpy_multidimensional.png?raw=true)

In [12]:
# definimos un array tridimensional
# en este caso estamos creando un array de números enteros entre el 10 y el 100 con
# 2 matrices, 3 filas y 5 columnas

tridimensional = np.random.randint(10,100, (2,3,5))
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# accedemos al primer array y al elemento que está en la fila 2 y la columna 4

print("\n---------------------------\n")
print(f"El elemento de la 1ª matriz, 2ª fila y 4ª columna es : \n {tridimensional[0,1,3]}")

El array multidimensional que tenemos es: 
 [[[52 82 28 22 75]
  [75 46 50 26 26]
  [61 84 68 49 78]]

 [[81 57 13 77 49]
  [74 41 14 47 45]
  [66 49 78 11 97]]]

---------------------------

El elemento de la 1ª matriz, 2ª fila y 4ª columna es : 
 26


In [11]:
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# primer array primera fila y todas las columnas

print("\n---------------------------\n")
print(f"Los elementos del 1ª matriz, 1ª fila y todas las columnas  : \n {tridimensional[0,0, :]}")

El array multidimensional que tenemos es: 
 [[[53 55 39 16 97]
  [93 72 56 36 69]
  [64 12 76 44 39]]

 [[36 78 84 75 72]
  [59 97 19 77 30]
  [81 56 79 63 33]]]

---------------------------

Los elementos del 1ª matriz, 1ª fila y todas las columnas  : 
 [53 55 39 16 97]
