In [1]:
import numpy as np

# 1 
Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [66]:
array =  np.random.randint(34, 99, (4, 3))
array

array([[63, 73, 67],
       [63, 91, 57],
       [47, 43, 86],
       [44, 50, 45]])

In [6]:
array.shape

(4, 3)

In [7]:
array.size

12

In [9]:
array.dtype

dtype('int32')

# 2 
Crea dos arrays (unidimensional, bidimensional) usando el método np.array(). Las listas para crear los arrays son las siguientes:

In [ ]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [11]:
np.array(lista1)

array([34, 56, 71, 98, 10])

In [12]:
np.array(lista2)

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

# 3
Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

- El primer elemento.

- Lo elementos que están en posición impar.

- Los cuatro primeros elementos.

- Los últimos tres elementos.

- Los elementos entre el 4 y el 8 (incluido).

In [16]:
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [23]:
arrayunid = np.random.randint(1, 51, 50)
arrayunid

array([11, 44, 47,  9, 16, 23, 24, 13, 16, 27, 36,  9, 49, 46, 24, 37, 20,
       30, 43, 31,  9, 48,  5, 19, 25, 40, 16, 25, 15, 45, 45,  9,  5,  4,
       37, 34, 44, 37, 49, 14, 22, 26,  5, 36, 23,  3,  1, 43, 28, 44])

In [24]:
arrayunid[0]

11

In [27]:
arrayunid[::2]

array([11, 47, 16, 24, 16, 36, 49, 24, 20, 43,  9,  5, 25, 16, 15, 45,  5,
       37, 44, 49, 22,  5, 23,  1, 28])

In [29]:
arrayunid[:4]

array([11, 44, 47,  9])

In [41]:
arrayunid[-3:]

array([43, 28, 44])

In [31]:
arrayunid[3:8]

array([ 9, 16, 23, 24, 13])

# 4 
Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

- La primera fila y todas las columnas.

- Todas las filas pares.

- La primera columna y todas las filas.

In [36]:
a = np.random.randint(1,20, (4, 5))
a

array([[10,  2, 13,  2,  2],
       [13,  1,  9, 15,  1],
       [10, 12, 11, 18,  1],
       [ 4,  6,  2, 11,  7]])

In [55]:
a[0, :][::]

array([10,  2, 13,  2,  2])

In [52]:
a[0,0:]

array([10,  2, 13,  2,  2])

In [46]:
a[0:]

array([[10,  2, 13,  2,  2],
       [13,  1,  9, 15,  1],
       [10, 12, 11, 18,  1],
       [ 4,  6,  2, 11,  7]])

In [42]:
a[0::2]

array([[10,  2, 13,  2,  2],
       [10, 12, 11, 18,  1]])

# 5
Crea un array bidimensional con 20 elementos aleatorios entre 0 y 50 con el método que prefieras y:

- Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

- Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [67]:
array = np.random.randint(0, 51, (4, 5))
print("Array original:")
print(array)

# Crear una máscara para los valores mayores a 30 y menores a 10
mascara = (array > 30) | (array < 10)

# Crear un array de etiquetas basado en la máscara
etiquetas = np.where(mascara, "objetivo", "no es mi objetivo")
print("\nMáscara aplicada:")
print(etiquetas)

# Multiplicar el array por 10
array_escalado = array * 10
print("\nArray multiplicado por 10:")
print(array_escalado)

Array original:
[[49  5  4 44 19]
 [50 49 43 25 36]
 [ 4 23 41  2 36]
 [44 11 11 44 29]]

Máscara aplicada:
[['objetivo' 'objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo' 'objetivo']
 ['objetivo' 'no es mi objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'no es mi objetivo']]

Array multiplicado por 10:
[[490  50  40 440 190]
 [500 490 430 250 360]
 [ 40 230 410  20 360]
 [440 110 110 440 290]]


# 6
Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

- Suma el primer array con el segundo.

- Aplicar la potencia para el primer array elevado al segundo.

In [68]:
import numpy as np

# Crear un array bidimensional de 4x5 con valores aleatorios entre 0 y 50
array = np.random.randint(0, 51, (4, 5))
print("Array original:")
print(array)

# Crear una máscara para los valores mayores a 30 y menores a 10
mascara = (array > 30) | (array < 10)

# Crear un array de etiquetas basado en la máscara
etiquetas = np.where(mascara, "objetivo", "no es mi objetivo")
print("\nMáscara aplicada:")
print(etiquetas)

# Multiplicar el array por 10
array_escalado = array * 10
print("\nArray multiplicado por 10:")
print(array_escalado)

# Crear un segundo array con la misma forma que el primero
array2 = np.random.randint(0, 51, (4, 5))
print("\nSegundo array:")
print(array2)

# Sumar el primer array con el segundo
suma_arrays = array + array2
print("\nSuma de los dos arrays:")
print(suma_arrays)

# Aplicar la potencia del primer array elevado al segundo
potencia_arrays = np.power(array, array2)
print("\nPrimer array elevado al segundo:")
print(potencia_arrays)


Array original:
[[47 19 30  5 14]
 [22 21 24  8 24]
 [ 5 24 40 12 26]
 [22 12  3 12 31]]

Máscara aplicada:
[['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'no es mi objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo' 'objetivo'
  'no es mi objetivo']
 ['objetivo' 'no es mi objetivo' 'objetivo' 'no es mi objetivo'
  'no es mi objetivo']
 ['no es mi objetivo' 'no es mi objetivo' 'objetivo' 'no es mi objetivo'
  'objetivo']]

Array multiplicado por 10:
[[470 190 300  50 140]
 [220 210 240  80 240]
 [ 50 240 400 120 260]
 [220 120  30 120 310]]

Segundo array:
[[18 44 19 23 36]
 [17 23 25 30 46]
 [36 38 47 41  8]
 [19 10  1  5  0]]

Suma de los dos arrays:
[[65 63 49 28 50]
 [39 44 49 38 70]
 [41 62 87 53 34]
 [41 22  4 17 31]]

Primer array elevado al segundo:
[[ 1482186145  1644676785   829947904 -1883073043           0]
 [ 1284898816   687269853           0           0           0]
 [ 1530182129           0           0           0 -1626332928]
 [ 

# 7
Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

- Calcula:

        - La media de los elementos

        - La media de las columnas y redondéalo a dos decimales

        - El valor máximo de cada fila

        - El valor mínimo de cada fila

        - Hay algun valor que sea mayor que 90 en tu array

        - Donde los podemos encontrar, cuáles son sus índices

        - Ordena el array de mayor a menor

📝 NOTA En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos.

In [69]:
# Crear un array bidimensional de 4x5 con valores aleatorios entre 0 y 100
array = np.random.randint(0, 101, (4, 5))
print("Array original:")
print(array)

# Calcular la media de los elementos
total_media = np.mean(array)
print("\nMedia de los elementos:", total_media)

# Calcular la media de las columnas y redondear a dos decimales
media_columnas = np.round(np.mean(array, axis=0), 2)
print("\nMedia de las columnas:", media_columnas)

# Obtener el valor máximo de cada fila
max_filas = np.max(array, axis=1)
print("\nValor máximo de cada fila:", max_filas)

# Obtener el valor mínimo de cada fila
min_filas = np.min(array, axis=1)
print("\nValor mínimo de cada fila:", min_filas)

# Comprobar si hay algún valor mayor que 90
hay_mayor_90 = np.any(array > 90)
print("\n¿Hay algún valor mayor que 90?:", hay_mayor_90)

# Obtener los índices de los valores mayores a 90
indices_mayor_90 = np.argwhere(array > 90)
print("\nÍndices de los valores mayores a 90:", indices_mayor_90)

# Ordenar el array de mayor a menor
array_ordenado = np.sort(array, axis=None)[::-1]
print("\nArray ordenado de mayor a menor:")
print(array_ordenado)

Array original:
[[48 29 59 29 99]
 [ 7  8 92 79 94]
 [32 18 89 27 88]
 [93 60 46 91 40]]

Media de los elementos: 56.4

Media de las columnas: [45.   28.75 71.5  56.5  80.25]

Valor máximo de cada fila: [99 94 89 93]

Valor mínimo de cada fila: [29  7 18 40]

¿Hay algún valor mayor que 90?: True

Índices de los valores mayores a 90: [[0 4]
 [1 2]
 [1 4]
 [3 0]
 [3 3]]

Array ordenado de mayor a menor:
[99 94 93 92 91 89 88 79 60 59 48 46 40 32 29 29 27 18  8  7]
