# Instalar NumPy

In [ ]:
#path\to\your\env\Scripts\activate


In [2]:
pip install numpy 


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install numpy 


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
pip install

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.


ERROR: You must give at least one requirement to install (see "pip help install")


In [12]:
pip help install

Note: you may need to restart the kernel to use updated packages.

Usage:   
  c:\ProgramData\anaconda3\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  c:\ProgramData\anaconda3\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  c:\ProgramData\anaconda3\python.exe -m pip install [options] [-e] <vcs project url> ...
  c:\ProgramData\anaconda3\python.exe -m pip install [options] [-e] <local project path> ...
  c:\ProgramData\anaconda3\python.exe -m pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:
  -r, --requirement <file>    Install from the given requirements file. This
  

In [4]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np

In [14]:
print(np.__version__)

1.26.4


## ¿Qué es un array?

Un array, también conocido como *matriz o arreglo*, es una estructura de datos que permite almacenar una colección de elementos del mismo tipo.
Los arrays son utilizados para **organizar y manipular conjuntos de datos de manera eficiente**. En un array, los elementos están dispuestos en una **secuencia ordenada** y **se accede a ellos mediante un índice**. Al igual que hacíamos en listas, la indexación comienza en 0.

Los arrays pueden tener una o varias dimensiones. 
1. Un array unidimensional se representa como una secuencia lineal de elementos, similar a una lista en Python: [1, 2, 3, 4, 5]
2. Un array bidimensional se organiza en filas y columnas, formando una especie de tabla o matriz. Cada elemento en un array bidimensional se identifica mediante dos índices: uno para la fila y otro para la columna. Por ejemplo:

In [6]:
#1.       
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [7]:
#2.      
a = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

# si quisieras acceder al número 6 tendrías que elegir la fila 2 y la columna 3, como los índices en python empiezan en 0, los índices que tendrías que usar son: 
a [1][2] 
# esto nos devolvería el valor 6. 
# donde [1] representa la posicion de la fila
# donde [2] representa la posicion de la columna

6

Los arrays pueden tener más dimensiones, como los **arrays tridimensionales, cuatridimensionales, y así sucesivamente**. Estas estructuras de datos multidimensionales *son útiles para representar y manipular datos más complejos, como imágenes, volúmenes de datos científicos, tensores en aprendizaje automático, entre otros, aspectos que nosotras no trabajaremos normalente como analistas.*

# Indexación

Se utiliza para acceder a elementos especificando sus índices dentro del array, de una forma muy similar a como lo hacíamos con listas.
Si recordamos de las listas:

Empezabamos a contar las posiciones de nuestros elementos desde 0. En NumPy será igual.


Si queremos acceder a un subconjunto de elementos de nuestra lista usabamos la siguiente sintaxis:

In [8]:
'''lista[start:stop:step]'''

# ejemplo:
lst = [12,20,3,45,6,23,81,93]

# seleccionamos desde el elemento 3 (incluido) hasta el final
lst[3:] 
[45, 6, 23, 81, 93]


# seleccionamos desde el elemento 3 hasta el 5. ⚠️ Recordamos que en el límite superior el valor que especificamos NO SE INCLUYE
lst[3:6]
[45, 6, 23]


# seleccionamos los 4 primeros elementos
lst[:4]
[12, 20, 3, 45]


# seleccionamos todos los elementos que están en posición impar
lst[1::2]
[12, 3, 6, 81]

[12, 3, 6, 81]

In [10]:
arr_3d = np.random.randint(1,100, (2,3,3))
arr_3d

array([[[76,  4, 13],
        [34, 47, 36],
        [83, 16, 33]],

       [[52, 59, 81],
        [66, 48, 88],
        [46, 26, 80]]])

# Filtrar

**Filtrado de datos en arrays**      
***Filtrado con condiciones***

El filtrado de datos en arrays de NumPy es una técnica para seleccionar elementos específicos de un array basado en ciertas condiciones. NumPy proporciona una forma eficiente de filtrar datos utilizando operaciones booleanas.

Los pasos para poder filtrar datos en arrays de NumPy son:

1. Creación de una máscara booleana: En el filtrado de datos, primero necesitamos crear una máscara booleana, que es un array booleano que tiene la misma forma que el array original. La máscara booleana contiene valores True o False, donde True indica que un elemento cumple una determinada condición y False indica que no la cumple. Por ejemplo:

In [12]:
array = np.array([1, 2, 3, 4, 5])
mascara = array > 3  # Crear una máscara booleana donde los elementos mayores que 3 son True
mascara

array([False, False, False,  True,  True])

2. Aplicación de la máscara booleana: Una vez que tenemos la máscara booleana, podemos aplicarla para filtrar los datos del array original. Puedes utilizar la máscara booleana como índice para seleccionar los elementos correspondientes del array original. Por ejemplo:

In [13]:
elementos_filtrados = array[mascara]  # Filtrar los elementos del array original usando la máscara booleana
elementos_filtrados

array([4, 5])

# Funciones

**Funciones universales o ufuncs**

Las Funciones Universales (ufuncs) de NumPy permiten realizar operaciones eficientes elemento por elemento en arrays de NumPy. Estas funciones proporcionan un rendimiento optimizado y una amplia variedad de operaciones.

*Operaciones estadísticas*

In [18]:
np.mean(a)

5.0

In [19]:
np.mean(arr_3d)

49.333333333333336

Calcula la media de todos los elementos del array. La media es una medida estadística que se utiliza para obtener el valor promedio de un conjunto de datos numéricos. Para calcular la media, se suman todos los valores y se dividen por la cantidad total de valores.

Este método nos permite elegir el eje sobre el que queremos calcular la media. Para eso tendremos que usar el parámetro axis, donde:

In [ ]:

axis = 0 : nos calculará la media para cada columna de nuestro array.

Cuando pasamos este parámetro la función np.mean produce un nuevo array con los resultados.

## Resumen

- NumPy es una librería especializada para el calculo numérico.
- Utiliza los array como estructura de datos.
- Solo permite datos de un mismo tipo. Ya sea: Bool, Int, Float, str ...
- Puede tener múltiples dimensiones:

            1D

            2D

            3D

            N-D

- Podemos crear arrays utilizando listas.
- Para operar entre arrays necesitamos que ambos contengan los mismos tipos de datos.
        - En sumas y restas han de tener las mismas dimensiones
        - En multiplicación y division se debe cumplir la regla de multiplicación de matrices.
- Podemos realizar operaciones entre arrays y escalares (siendo un escalar un número)
- Creación de arrays:
    Podemos tener arrays de diferentes dimensiones:

    Una dimensión : np.array(lista)

    Dos dimensiones : np.array(lista1, lista)

    Tres dimensiones: np.array(lista1(lista), lista2(lista))


- Métodos de arrays:

                        .shape: Nos devuelve la forma del array.

                                - En un array bidimensional nos devuelve: numero filas X numero de columnas

                                - En un array multidimensionales: numero de matrices X numero de filas X numero de columnas

                        .size: Nos devuelve el tamaño del array, que es el número de elementos.

                        .ndim: Nos devuelve el número de dimensiones del array.

                        .dtype: Nos devuelve el tipo de dato que contiene nuestro array.

- Métodos de creación de arrays:

        np.random.randint(): nos genera un array de X dimensiones con números aleatorios ENTEROS

       
        np.random.randint(1, 20, (2,3,4))
        np.random.rand(): nos genera un array de X dimensiones con números aleatorios entre 0-1. PARA ESPECIFICAR LA FORMA Y DIMENSIONES LO PONEMOS SIN PARENTESIS

        array2 = np.random.rand(2,4)
        np.random.random_sample(): nos genera un array de X dimensiones con números aleatorios entre 0-1. PARA ESPECIFICAR LA FORMA Y DIMENSIONES LO PONEMOS CON PARENTESIS

        array = np.random.random_sample((3,4,5))
        np.ones(): nos genera un array solo de 1.

        unos = np.ones((2,3), dtype = int)
        el parametro dtype nos permite "castear" el tipo de dato a int
        np.zeros(): nos genera un array solo de 0.

        ceros = np.zeros((2,3,4), dtype = int)
        np.empty(): nos genera un array vacío con la forma del array que le pasemos.

        vacio = np.empty((2,3))
        np.array(): nos genera arrays a partir de una lista, o de una lista de listas.

        np.arange(): SOLO CREA ARRAYS UNIDIMENSIONAL.

- Podemos hacer operaciones en NumPy:

        Podemos sumar con: + o np.add()

        Restar con: -, np.subtract()

        Multiplicar con: *, np.multiply()

        Dividir con: /, np.divide()

        📌 Podemos hacer todas las operaciones que queramos!!!!

        Podemos hacer operaciones con escalares, números enteros o decimales.

- La Indexación en arrays es como en listas, siempre empieza en cero y siempre debe de ir entre corchetes.

- Indexación en función de las dimensiones

        Unidimensional: array[i], donde [i]= columna

        Bidimensional: array [i,j] = array[i][j], donde [i] = fila, [j]= columna

        Multimensional: array[i,j,k] = array[i][j][k], donce [i] = array, [j] = fila, [k] = columna

- Indexación basado en rangos:

        Unidimensional: array[inicio:fin:salto]

        Bidimensional : array[inicio:fin:salto,inicio:fin:salto ] = array[inicio:fin:salto][inicio:fin:salto ]

        Multimensional: array[inicio:fin:salto,inicio:fin:salto,inicio:fin:salto ] = array[inicio:fin:salto][inicio:fin:salto ][inicio:fin:salto ]

- Podemos filtrar aplicando operadores <, >, >=, <=, ==.

    array[array (operador) condicion]

        : Eg array[array > condicion]

    Si queremos meter más de una condición: & o |

    array[array (operador) condicion1 anidamiento array (operador) condicion2]

        : Eg array[(array < 2) | (array > 5)]

## Métodos:

np.transpose(): invierte los ejes de nuestra matriz o si se le especifica el orden, nos permuta los ejes de la matriz.

np.swapaxes(): intercambia dos ejes de la matriz, indicando sobre que ejes queremos realizar la operación

np.reshape(): cambia la forma de la matriz a la forma especificada.

np.copy(): realiza una copia completa de un array NumPy, incluyendo sus datos y su estructura.

np.flatten(): se utiliza para convertir un array multidimensional en un array unidimensional, es decir, aplana el array.

