In [298]:
import pandas as pd
import numpy as np

In [299]:
df_proyect = pd.read_csv('data.csv')
print(df_proyect)

      Unnamed: 0 age attrition businesstravel    dailyrate  \
0              0  51        No            NaN  2015.722222   
1              1  52        No            NaN  2063.388889   
2              2  42        No  travel_rarely  1984.253968   
3              3  47        No  travel_rarely  1771.404762   
4              4  46        No            NaN  1582.771346   
...          ...  ..       ...            ...          ...   
1673        1673  43        No            NaN   488.944444   
1674        1674  47        No            NaN  1973.984127   
1675        1675  29        No  travel_rarely   290.035510   
1676        1676  47        No  travel_rarely  1032.487286   
1677        1677  32        No            NaN   556.256661   

                    department  distancefromhome  education    educationfield  \
0                          NaN                 6          3               NaN   
1                          NaN                 1          4     Life Sciences   
2      Resea

Código que mejore la visualización del DataFrame

In [300]:
from IPython.display import display

In [301]:
display(df_proyect)

Unnamed: 0 age attrition businesstravel    dailyrate  \
0              0  51        No            NaN  2015.722222   
1              1  52        No            NaN  2063.388889   
2              2  42        No  travel_rarely  1984.253968   
3              3  47        No  travel_rarely  1771.404762   
4              4  46        No            NaN  1582.771346   
...          ...  ..       ...            ...          ...   
1673        1673  43        No            NaN   488.944444   
1674        1674  47        No            NaN  1973.984127   
1675        1675  29        No  travel_rarely   290.035510   
1676        1676  47        No  travel_rarely  1032.487286   
1677        1677  32        No            NaN   556.256661   

                    department  distancefromhome  education    educationfield  \
0                          NaN                 6          3               NaN   
1                          NaN                 1          4     Life Sciences   
2      Research & Development                  4          2  Technical Degree   
3                          NaN                 2          4           Medical   
4                          NaN                 3          3  Technical Degree   
...                        ...               ...        ...               ...   
1673                       NaN               -26          3           Medical   
1674                       NaN                26          4               NaN   
1675                       NaN                15          3               NaN   
1676                       NaN                 4          3     Life Sciences   
1677                       NaN                 2          2     Life Sciences   

      employeecount  ...  yearsatcompany  yearsincurrentrole  \
0                 1  ...              20                 NaN   
1                 1  ...              33                 NaN   
2                 1  ...              22                 NaN   
3                 1  ...              20                 NaN   
4                 1  ...              19                 NaN   
...             ...  ...             ...                 ...   
1673              1  ...               3                 NaN   
1674              1  ...               5                 NaN   
1675              1  ...               6                 NaN   
1676              1  ...              22                 NaN   
1677              1  ...               8                 NaN   

      yearssincelastpromotion  yearswithcurrmanager  sameasmonthlyincome  \
0                          15                    15            16280,83$   
1                          11                     9                  NaN   
2                          11                    15                  NaN   
3                           5                     6            14307,50$   
4                           2                     8            12783,92$   
...                       ...                   ...                  ...   
1673                        1                     2             3949,17$   
1674                        1                     0            15943,72$   
1675                        1                     5                  NaN   
1676                       14                    10             8339,32$   
1677                        0                     7                  NaN   

      datebirth      salary                       roledepartament  \
0          1972  195370,00$                                   NaN   
1          1971  199990,00$                                   NaN   
2          1981  192320,00$   ManaGER  -  Research & Development    
3          1976  171690,00$                                   NaN   
4          1977         NaN                                   NaN   
...         ...         ...                                   ...   
1673       1980         NaN                                   NaN   
1674       1976  191324,62$                           

Mostrar las columnas para filtrar datos de manera ordenada

In [302]:
df_proyect.shape
print(f'Tenemos un número de filas de {df_proyect.shape[0]} y un número de columnas de {df_proyect.shape[1]}')

Tenemos un número de filas de 1678 y un número de columnas de 42


In [303]:
display(df_proyect.sample(10))

Unnamed: 0 age attrition     businesstravel    dailyrate  \
715          715  42        No                NaN   625.444444   
1119        1119  29        No                NaN   649.380952   
1349        1349  40       Yes         non-travel  1361.285714   
1164        1164  35        No  travel_frequently   556.256661   
771          771  39        No                NaN  1032.487286   
1581        1581  32        No                NaN   556.730159   
756          756  38        No  travel_frequently   556.256661   
865          865  37        No         non-travel  1032.487286   
1571        1571  34        No                NaN   550.642857   
226          226  40        No      travel_rarely   556.256661   

                    department  distancefromhome  education educationfield  \
715                        NaN                 1          2  Life Sciences   
1119                       NaN                 1          3            NaN   
1349                       NaN                24          3            NaN   
1164                       NaN                18          4  Life Sciences   
771    Research & Development                 10          1        Medical   
1581                       NaN                10          3      Marketing   
756                        NaN                10          4            NaN   
865                        NaN                 1          4        Medical   
1571                       NaN                21          4            NaN   
226                        NaN                 2          3  Life Sciences   

      employeecount  ...  yearsatcompany  yearsincurrentrole  \
715               1  ...               4                 NaN   
1119              1  ...               3                 NaN   
1349              1  ...               1                 NaN   
1164              1  ...              10                 NaN   
771               1  ...               4                 NaN   
1581              1  ...              10                 NaN   
756               1  ...               6                 NaN   
865               1  ...               5                 NaN   
1571              1  ...              10                 NaN   
226               1  ...               9                 NaN   

      yearssincelastpromotion  yearswithcurrmanager  sameasmonthlyincome  \
715                         0                     2                  NaN   
1119                        0                     2             5245,00$   
1349                        0                     0                  NaN   
1164                        0                     2             4492,84$   
771                         2                     2             8339,32$   
1581                        0                     8             4496,67$   
756                         1                     2             4492,84$   
865                         0                     2             8339,32$   
1571                        5                     7                  NaN   
226                         8                     8                  NaN   

      datebirth      salary                                 roledepartament  \
715        1981   60620,00$                                             NaN   
1119       1994   62940,00$                                             NaN   
1349       1983  131940,00$                                             NaN   
1164       1988   53914,11$                                             NaN   
771        1984  100071,84$   RESeArch dIREcToR  -  Research & Development    
1581       1991         NaN                                             NaN   
756        1985   53914,11$                                             NaN   
865        1986  100071,84$                                             NaN   
1571       1989   53370,00$                                             NaN   
226        1983   53914,11$                                             NaN   

     num

In [304]:
df_proyect.columns

Index(['Unnamed: 0', 'age', 'attrition', 'businesstravel', 'dailyrate',
       'department', 'distancefromhome', 'education', 'educationfield',
       'employeecount', 'employeenumber', 'environmentsatisfaction', 'gender',
       'hourlyrate', 'jobinvolvement', 'joblevel', 'jobrole',
       'jobsatisfaction', 'maritalstatus', 'monthlyincome', 'monthlyrate',
       'numcompaniesworked', 'over18', 'overtime', 'percentsalaryhike',
       'performancerating', 'relationshipsatisfaction', 'standardhours',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager',
       'sameasmonthlyincome', 'datebirth', 'salary', 'roledepartament',
       'numberchildren', 'remotework'],
      dtype='object')

In [305]:
df_proyect.columns.get_loc("salary") #posición de una columna

38

In [306]:
display(df_proyect.describe())

Unnamed: 0    dailyrate  distancefromhome    education  employeecount  \
count  1678.000000  1678.000000       1678.000000  1678.000000         1678.0   
mean    838.500000   668.079714          4.504172     2.932658            1.0   
std     484.541192   470.787298         14.652066     1.024270            0.0   
min       0.000000   104.103175        -49.000000     1.000000            1.0   
25%     419.250000   290.035510          2.000000     2.000000            1.0   
50%     838.500000   556.256661          5.000000     3.000000            1.0   
75%    1257.750000   971.956349         11.000000     4.000000            1.0   
max    1677.000000  2063.388889         29.000000     5.000000            1.0   

       employeenumber  environmentsatisfaction       gender  hourlyrate  \
count     1678.000000              1678.000000  1678.000000  411.000000   
mean       809.859952                 4.264005     0.398689   83.140768   
std        467.084867                 6.912695     0.489774   57.272101   
min          1.000000                 1.000000     0.000000   13.012897   
25%        403.250000                 2.000000     0.000000   36.254439   
50%        813.500000                 3.000000     0.000000   69.532083   
75%       1215.750000                 4.000000     1.000000  116.987103   
max       1614.000000                49.000000     1.000000  255.963294   

       jobinvolvement  ...  numcompaniesworked  percentsalaryhike  \
count     1678.000000  ...         1678.000000        1678.000000   
mean         2.740763  ...            2.670441          15.154350   
std          0.710359  ...            2.501133           3.649607   
min          1.000000  ...            0.000000          11.000000   
25%          2.000000  ...            1.000000          12.000000   
50%          3.000000  ...            2.000000          14.000000   
75%          3.000000  ...            4.000000          18.000000   
max          4.000000  ...            9.000000          25.000000   

       relationshipsatisfaction  stockoptionlevel  trainingtimeslastyear  \
count               1678.000000       1678.000000            1678.000000   
mean                   2.700238          0.787843               2.795590   
std                    1.079494          0.843252               1.288657   
min                    1.000000          0.000000               0.000000   
25%                    2.000000          0.000000               2.000000   
50%                    3.000000          1.000000               3.000000   
75%                    4.000000          1.000000               3.000000   
max                    4.000000          3.000000               6.000000   

       yearsatcompany  yearssincelastpromotion  yearswithcurrmanager  \
count     1678.000000              1678.000000           1678.000000   
mean         7.124553                 2.241955              4.200238   
std          6.173837                 3.246554              3.554224   
min          0.000000                 0.000000              0.000000   
25%          3.000000                 0.000000              2.000000   
50%          5.000000                 1.000000              3.000000   
75%          9.000000                 3.000000              7.000000   
max         40.000000                15.000000             17.000000   

         datebirth  numberchildren  
count  1678.000000             0.0  
mean   1986.047080             NaN  
std       9.154908             NaN  
min    1963.000000             NaN  
25%    1980.000000             NaN  
50%    1987.000000             NaN  
75%    1993.000000             NaN  
max    2005.000000             NaN  

[8 rows x 22 columns]

Mostrar las columnas de tarea asignada

In [307]:
df_columnas_asignadas = df_proyect [['yearsatcompany', 'yearsincurrentrole',
    'yearssincelastpromotion', 'yearswithcurrmanager',
    'sameasmonthlyincome', 'datebirth', 'salary', 'roledepartament',
    'numberchildren', 'remotework']]

print(display(df_columnas_asignadas))

yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0                 20                NaN                       15   
1                 33                NaN                       11   
2                 22                NaN                       11   
3                 20                NaN                        5   
4                 19                NaN                        2   
...              ...                ...                      ...   
1673               3                NaN                        1   
1674               5                NaN                        1   
1675               6                NaN                        1   
1676              22                NaN                       14   
1677               8                NaN                        0   

      yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                       15           16280,83$       1972  195370,00$   
1                        9                 NaN       1971  199990,00$   
2                       15                 NaN       1981  192320,00$   
3                        6           14307,50$       1976  171690,00$   
4                        8           12783,92$       1977         NaN   
...                    ...                 ...        ...         ...   
1673                     2            3949,17$       1980         NaN   
1674                     0           15943,72$       1976  191324,62$   
1675                     5                 NaN       1994   28111,13$   
1676                    10            8339,32$       1976  100071,84$   
1677                     7                 NaN       1991   53914,11$   

                           roledepartament  numberchildren remotework  
0                                      NaN             NaN        Yes  
1                                      NaN             NaN          1  
2      ManaGER  -  Research & Development              NaN          1  
3                                      NaN             NaN      False  
4                                      NaN             NaN          0  
...                                    ...             ...        ...  
1673                                   NaN             NaN        Yes  
1674                                   NaN             NaN      False  
1675                                   NaN             NaN      False  
1676                                   NaN             NaN        Yes  
1677                                   NaN             NaN          0  

[1678 rows x 10 columns]

None


In [308]:
df_proyect[['yearsatcompany', 'yearsincurrentrole',
    'yearssincelastpromotion', 'yearswithcurrmanager',
    'sameasmonthlyincome', 'datebirth', 'salary', 'roledepartament',
    'numberchildren', 'remotework']].describe()

yearsatcompany  yearssincelastpromotion  yearswithcurrmanager  \
count     1678.000000              1678.000000           1678.000000   
mean         7.124553                 2.241955              4.200238   
std          6.173837                 3.246554              3.554224   
min          0.000000                 0.000000              0.000000   
25%          3.000000                 0.000000              2.000000   
50%          5.000000                 1.000000              3.000000   
75%          9.000000                 3.000000              7.000000   
max         40.000000                15.000000             17.000000   

         datebirth  numberchildren  
count  1678.000000             0.0  
mean   1986.047080             NaN  
std       9.154908             NaN  
min    1963.000000             NaN  
25%    1980.000000             NaN  
50%    1987.000000             NaN  
75%    1993.000000             NaN  
max    2005.000000             NaN

- `count`: El número de observaciones no nulas en la columna.

- `mean`: La media en la columna.

- `std`: La desviación estándar, que mide la dispersión.

- `min`: El valor mínimo en el conjunto de datos.

- `25%`: El percentil 25, que representa el valor por debajo del cual se encuentra el 25% de los valores.

- `50%`: La mediana o percentil 50, que es el valor que divide el conjunto de datos en dos mitades iguales.

- `75%`: El percentil 75, que representa el valor por debajo del cual se encuentra el 75% de los valores.

- `max`: El valor máximo en el conjunto de datos.


Este método es para las columnas categóricas que son aquellas que contienen valores que representan categorías o grupos en lugar de números continuos.
🔹 Ejemplos de columnas categóricas:

    Género: "Masculino", "Femenino"
    Estado Civil: "Soltero", "Casado", "Divorciado"
    Tipo de Viaje: "Frecuente", "Ocasional"
    Departamento: "Ventas", "Marketing", "RRHH"
    Sí/No o Verdadero/Falso: "Sí", "No" o True, False

In [309]:
df_proyect[['yearsatcompany', 'yearsincurrentrole',
    'yearssincelastpromotion', 'yearswithcurrmanager',
    'sameasmonthlyincome', 'datebirth', 'salary', 'roledepartament',
    'numberchildren', 'remotework']].describe(include = "object").T

count unique  \
yearsincurrentrole     35     10   
sameasmonthlyincome  1189    493   
salary               1393    583   
roledepartament       312    301   
remotework           1678      5   

                                                                 top freq  
yearsincurrentrole                                               2,0   12  
sameasmonthlyincome                                         2342,59$  228  
salary                                                     53914,11$  270  
roledepartament       rESEArcH SCiEntIst  -  Research & Development     2  
remotework                                                         1  375

- `count`: El número de observaciones no nulas.

- `unique`: La cantidad de valores únicos.

- `top`: El valor más común en la columna.

- `freq`: La frecuencia del valor más común.

## Información general del DataFrame

In [363]:
display(df_columnas_asignadas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   yearsatcompany           1678 non-null   int64  
 1   yearsincurrentrole       35 non-null     object 
 2   yearssincelastpromotion  1678 non-null   int64  
 3   yearswithcurrmanager     1678 non-null   int64  
 4   sameasmonthlyincome      1189 non-null   object 
 5   datebirth                1678 non-null   int64  
 6   salary                   1393 non-null   object 
 7   roledepartament          312 non-null    object 
 8   numberchildren           0 non-null      float64
 9   remotework               1678 non-null   object 
dtypes: float64(1), int64(4), object(5)
memory usage: 131.2+ KB


None

## Valores únicos

In [310]:
df_proyect['yearsatcompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [311]:
df_proyect['yearsincurrentrole'].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [312]:
df_proyect['yearssincelastpromotion'].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [313]:
df_proyect['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

In [314]:
df_proyect['sameasmonthlyincome'].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

In [315]:
df_proyect['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

In [316]:
df_proyect['salary'].unique()

array(['195370,00$', '199990,00$', '192320,00$', '171690,00$', nan,
       '100071,84$', '53914,11$', '165950,00$', '199730,00$',
       '134020,00$', '132060,00$', '195450,00$', '180410,00$',
       '192460,00$', '107480,00$', '167520,00$', '62010,00$',
       '198450,00$', '40010,00$', '104470,00$', '191324,62$',
       '160640,00$', '32100,00$', '102660,00$', '104750,00$', '61620,00$',
       '47210,00$', '153407,07$', '28111,13$', '46150,00$', '169590,00$',
       '54060,00$', '59020,00$', '108550,00$', '59140,00$', '66460,00$',
       '139730,00$', '66870,00$', '47350,00$', '138720,00$', '190450,00$',
       '96130,00$', '115100,00$', '170460,00$', '36920,00$', '198470,00$',
       '23080,00$', '57470,00$', '104220,00$', '63470,00$', '23480,00$',
       '30720,00$', '124900,00$', '80200,00$', '170680,00$', '89430,00$',
       '192720,00$', '55770,00$', '26910,00$', '74030,00$', '88230,00$',
       '35790,00$', '177790,00$', '182130,00$', '135770,00$',
       '191900,00$', '171230,

In [317]:
df_proyect['roledepartament'].unique()

array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

In [318]:
df_proyect['numberchildren'].unique()

array([nan])

In [319]:
df_proyect['remotework'].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

## Valores duplicados

In [365]:
df_columnas_asignadas.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1673     True
1674     True
1675     True
1676     True
1677     True
Length: 1678, dtype: bool

In [366]:
df_columnas_asignadas.duplicated().sum()

78

In [371]:
df_proyect.columns

Index(['Unnamed: 0', 'age', 'attrition', 'businesstravel', 'dailyrate',
       'department', 'distancefromhome', 'education', 'educationfield',
       'employeecount', 'employeenumber', 'environmentsatisfaction', 'gender',
       'hourlyrate', 'jobinvolvement', 'joblevel', 'jobrole',
       'jobsatisfaction', 'maritalstatus', 'monthlyincome', 'monthlyrate',
       'numcompaniesworked', 'over18', 'overtime', 'percentsalaryhike',
       'performancerating', 'relationshipsatisfaction', 'standardhours',
       'stockoptionlevel', 'totalworkingyears', 'trainingtimeslastyear',
       'worklifebalance', 'yearsatcompany', 'yearsincurrentrole',
       'yearssincelastpromotion', 'yearswithcurrmanager',
       'sameasmonthlyincome', 'datebirth', 'salary', 'roledepartament',
       'numberchildren', 'remotework'],
      dtype='object')

#### Debemos asegurarnos en qué columnas puede ser un problema tener valores duplicados

In [377]:
df_proyect.duplicated(subset ='employeenumber').sum()

64

### TENEMOS 64 DUPLICADOS EN EMPLOYEENUMBER, IMPORTANTE REVISARLO

 ## Tipo de datos por columnas
 
    Seleccionar todas las columnas numéricas
    df.select_dtypes(include=['int', 'float'])

    #Seleccionar todas las columnas de tipo objeto (cadenas de texto)
    df.select_dtypes(include='object')

    Seleccionar todas las columnas excepto las numéricas
    df.select_dtypes(exclude=['int', 'float'])

    Seleccionar todas las columnas excepto las de tipo objeto (cadenas de texto)
    df.select_dtypes(exclude='object')

In [320]:
df_columnas_asignadas.select_dtypes(include=['int', 'float'])

yearsatcompany  yearssincelastpromotion  yearswithcurrmanager  \
0                 20                       15                    15   
1                 33                       11                     9   
2                 22                       11                    15   
3                 20                        5                     6   
4                 19                        2                     8   
...              ...                      ...                   ...   
1673               3                        1                     2   
1674               5                        1                     0   
1675               6                        1                     5   
1676              22                       14                    10   
1677               8                        0                     7   

      datebirth  numberchildren  
0          1972             NaN  
1          1971             NaN  
2          1981             NaN  
3          1976             NaN  
4          1977             NaN  
...         ...             ...  
1673       1980             NaN  
1674       1976             NaN  
1675       1994             NaN  
1676       1976             NaN  
1677       1991             NaN  

[1678 rows x 5 columns]

In [321]:
df_columnas_asignadas.select_dtypes(include='object')

yearsincurrentrole sameasmonthlyincome      salary  \
0                   NaN           16280,83$  195370,00$   
1                   NaN                 NaN  199990,00$   
2                   NaN                 NaN  192320,00$   
3                   NaN           14307,50$  171690,00$   
4                   NaN           12783,92$         NaN   
...                 ...                 ...         ...   
1673                NaN            3949,17$         NaN   
1674                NaN           15943,72$  191324,62$   
1675                NaN                 NaN   28111,13$   
1676                NaN            8339,32$  100071,84$   
1677                NaN                 NaN   53914,11$   

                           roledepartament remotework  
0                                      NaN        Yes  
1                                      NaN          1  
2      ManaGER  -  Research & Development           1  
3                                      NaN      False  
4                                      NaN          0  
...                                    ...        ...  
1673                                   NaN        Yes  
1674                                   NaN      False  
1675                                   NaN      False  
1676                                   NaN        Yes  
1677                                   NaN          0  

[1678 rows x 5 columns]

## Extracción datos columna 'yearsatcompany'

In [322]:
df_columnas_asignadas ['yearsatcompany']

0       20
1       33
2       22
3       20
4       19
        ..
1673     3
1674     5
1675     6
1676    22
1677     8
Name: yearsatcompany, Length: 1678, dtype: int64

Compruebo tipo de dato de la columna

In [323]:
df_columnas_asignadas ['yearsatcompany'].dtypes


dtype('int64')

Para visualizar los valores

In [324]:
print(df_columnas_asignadas['yearsatcompany'].unique())

[20 33 22 19 21 18 24 31 26 16 23 15 17 32 14 13 25 12 11 37 40 36 27 29
 10  9 30  8  7 34  6  5  4  2  3  1  0]


Compruebo si hay nulos en esta columna con el uso de máscara

In [325]:
mascara1 = df_columnas_asignadas ['yearsatcompany'].isnull()

df_nulos1 = df_columnas_asignadas[mascara1]

if df_nulos1.empty: # aquí no podemos igualas a 0 o True/False, en los DataFrame hay que usar la condición de si está vacío o no
    print ('No hay valores nulos')

else:
    print(f'Los valores nulos de la columna son {df_nulos1}')

No hay valores nulos


Compruebo si hay datos vacíos

In [326]:
df_vacios = df_columnas_asignadas[df_columnas_asignadas['yearsatcompany'] == " "]

if df_vacios.empty:
    print('No hay datos vacíos')
else:
    print(f'Los valores vacíos de la columna son {df_vacios}')

No hay datos vacíos


Se puden combinar ambas condiciones

In [327]:
df_vacios_nulos = df_columnas_asignadas[df_columnas_asignadas['yearsatcompany'].isnull() | (df_columnas_asignadas['yearsatcompany'] == "")]
print(df_vacios_nulos)

Empty DataFrame
Columns: [yearsatcompany, yearsincurrentrole, yearssincelastpromotion, yearswithcurrmanager, sameasmonthlyincome, datebirth, salary, roledepartament, numberchildren, remotework]
Index: []


Compruebo si todos los valores son integers

In [328]:
df_columnas_asignadas['yearsatcompany'].values

array([20, 33, 22, ...,  6, 22,  8])

## Extracción datos columna 'yearsincurrentrole'
#### cuántos años ha trabajado una persona en su puesto de trabajo actual.

In [329]:
df_columnas_asignadas['yearsincurrentrole']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1673    NaN
1674    NaN
1675    NaN
1676    NaN
1677    NaN
Name: yearsincurrentrole, Length: 1678, dtype: object

## Creo función para valores nulos y vacíos

In [330]:
def filtrado_nulos (df,columna):
    
    df_nulos =df[df[columna].isnull()]
    df[columna].isnull().sum()
    
    if df_nulos.empty: 
        print (f'No hay valores nulos en la columna {columna}')

    else:
        print(f'El número total de nulos de la columna es de {df[columna].isnull().sum()}')
        print(f'Los valores nulos de la columna {columna} son:')
        print(df_nulos[columna])

In [331]:
def filtrado_vacios (df,columna):
    
    df_vacios = df[df[columna] == " "]
    
    if df_vacios.empty:
        print (f'No hay valores vacíos en la columna {columna}')

    else:
        print(f'Los valores vacíos de la columna {columna} son:')
        print(df_vacios[columna])

Llamo a las funciones para cada columna

In [332]:
df_columnas_asignadas.columns

Index(['yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

## Extracción de datos columna yearsincurrentrole
#### número de años que una persona ha estado desempeñando su puesto actual en una empresa 


In [333]:
filtrado_nulos(df_columnas_asignadas,'yearsincurrentrole')
filtrado_vacios(df_columnas_asignadas,'yearsincurrentrole')

El número total de nulos de la columna es de 1643
Los valores nulos de la columna yearsincurrentrole son:
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1673    NaN
1674    NaN
1675    NaN
1676    NaN
1677    NaN
Name: yearsincurrentrole, Length: 1643, dtype: object
No hay valores vacíos en la columna yearsincurrentrole


In [334]:
df_columnas_asignadas['yearsincurrentrole'].values

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [335]:
df_columnas_asignadas['yearsincurrentrole'].dtypes

dtype('O')

## Extracción de datos columna yearssincelastpromotion
#### número de años que han pasado desde que un empleado recibió su última promoción dentro de la empresa 

In [336]:
df_columnas_asignadas['yearssincelastpromotion'].values

array([15, 11, 11, ...,  1, 14,  0])

In [337]:
df_columnas_asignadas['yearssincelastpromotion'].dtypes


dtype('int64')

In [338]:
filtrado_nulos(df_columnas_asignadas,'yearssincelastpromotion')
filtrado_vacios(df_columnas_asignadas,'yearssincelastpromotion')

No hay valores nulos en la columna yearssincelastpromotion
No hay valores vacíos en la columna yearssincelastpromotion


## Extracción de datos columna 'yearswithcurrmanager'
#### número de años que un empleado ha trabajado bajo la supervisión de su actual jefe o gerente. Este dato es útil para medir la estabilidad de la relación laboral entre el empleado y su jefe


In [339]:
filtrado_nulos(df_columnas_asignadas,'yearswithcurrmanager')
filtrado_vacios(df_columnas_asignadas,'yearswithcurrmanager')

No hay valores nulos en la columna yearswithcurrmanager
No hay valores vacíos en la columna yearswithcurrmanager


In [340]:
df_columnas_asignadas['yearswithcurrmanager'].values

array([15,  9, 15, ...,  5, 10,  7])

In [341]:
df_columnas_asignadas['yearswithcurrmanager'].dtypes

dtype('int64')

## Extracción de datos columna sameasmonthlyincome
#### indicador binario (Sí/No) que indica si el empleado tiene o no el mismo salario mensual que otros empleados en una categoría o grupo específico. Este tipo de columna puede ser útil para identificar la equidad salarial dentro de la empresa.

In [342]:
filtrado_nulos(df_columnas_asignadas,'sameasmonthlyincome')
filtrado_vacios(df_columnas_asignadas,'sameasmonthlyincome')

El número total de nulos de la columna es de 489
Los valores nulos de la columna sameasmonthlyincome son:
1       NaN
2       NaN
7       NaN
11      NaN
12      NaN
       ... 
1668    NaN
1671    NaN
1672    NaN
1675    NaN
1677    NaN
Name: sameasmonthlyincome, Length: 489, dtype: object
No hay valores vacíos en la columna sameasmonthlyincome


In [343]:
df_columnas_asignadas['sameasmonthlyincome'].values

array(['16280,83$', nan, nan, ..., nan, '8339,32$', nan], dtype=object)

In [344]:
df_columnas_asignadas['sameasmonthlyincome'].dtypes

dtype('O')

## Extracción de datos columna 'datebirth'

In [345]:
filtrado_nulos(df_columnas_asignadas,'datebirth')
filtrado_vacios(df_columnas_asignadas,'datebirth')

No hay valores nulos en la columna datebirth
No hay valores vacíos en la columna datebirth


In [346]:
df_columnas_asignadas['datebirth'].values

array([1972, 1971, 1981, ..., 1994, 1976, 1991])

In [347]:
df_columnas_asignadas['datebirth'].dtypes

dtype('int64')

## Extracción de datos columna salary

In [348]:
filtrado_nulos(df_columnas_asignadas,'salary')
filtrado_vacios(df_columnas_asignadas,'salary')

El número total de nulos de la columna es de 285
Los valores nulos de la columna salary son:
4       NaN
5       NaN
9       NaN
14      NaN
17      NaN
       ... 
1647    NaN
1649    NaN
1653    NaN
1658    NaN
1673    NaN
Name: salary, Length: 285, dtype: object
No hay valores vacíos en la columna salary


In [349]:
df_columnas_asignadas['salary'].values

array(['195370,00$', '199990,00$', '192320,00$', ..., '28111,13$',
       '100071,84$', '53914,11$'], dtype=object)

In [350]:
df_columnas_asignadas['salary'].dtype

dtype('O')

## Extracción de datos columna 'roledepartament'
#### rol o puesto específico

In [351]:
filtrado_nulos(df_columnas_asignadas,'roledepartament')
filtrado_vacios(df_columnas_asignadas,'roledepartament')

El número total de nulos de la columna es de 1366
Los valores nulos de la columna roledepartament son:
0       NaN
1       NaN
3       NaN
4       NaN
6       NaN
       ... 
1673    NaN
1674    NaN
1675    NaN
1676    NaN
1677    NaN
Name: roledepartament, Length: 1366, dtype: object
No hay valores vacíos en la columna roledepartament


In [352]:
df_columnas_asignadas['roledepartament'].values

array([nan, nan, ' ManaGER  -  Research & Development ', ..., nan, nan,
       nan], dtype=object)

In [353]:
df_columnas_asignadas['roledepartament'].dtype

dtype('O')

## Extracción de datos columna 'numberchildren'

In [354]:
filtrado_nulos(df_columnas_asignadas,'numberchildren')
filtrado_vacios(df_columnas_asignadas,'numberchildren')

El número total de nulos de la columna es de 1678
Los valores nulos de la columna numberchildren son:
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1673   NaN
1674   NaN
1675   NaN
1676   NaN
1677   NaN
Name: numberchildren, Length: 1678, dtype: float64
No hay valores vacíos en la columna numberchildren


In [355]:
df_columnas_asignadas['numberchildren'].values

array([nan, nan, nan, ..., nan, nan, nan])

In [356]:
df_columnas_asignadas['numberchildren'].dtype

dtype('float64')

## Extracción de datos columna 'remotework'
####  se utiliza para indicar si un empleado tiene la opción de trabajar de forma remota o si se espera que trabaje presencialmente en la oficina.

In [357]:
filtrado_nulos(df_columnas_asignadas,'remotework')
filtrado_vacios(df_columnas_asignadas,'remotework')

No hay valores nulos en la columna remotework
No hay valores vacíos en la columna remotework


In [358]:
df_columnas_asignadas['remotework'].values

array(['Yes', '1', '1', ..., 'False', 'Yes', '0'], dtype=object)

In [359]:
df_columnas_asignadas['remotework'].dtype

dtype('O')

¿Qué significa dtype('O')?

    dtype es una abreviatura de Data Type (tipo de dato), que es una propiedad de los arrays y objetos en pandas que especifica qué tipo de datos están almacenados.
    'O' hace referencia a "Object", un tipo genérico que pandas utiliza para almacenar datos que no pertenecen a tipos numéricos específicos o tipos más estructurados (como enteros, flotantes, fechas, etc.).

En el contexto de un DataFrame de pandas, si una columna tiene dtype('O'), significa que los valores de esa columna son objetos y no un tipo de dato numérico o una fecha, normalmente implicando que son cadenas de texto (strings) o valores mixtos.