
1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().
Las listas para crear los arrays son las siguientes

    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]

3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

    - El primer elemento.
    - Lo elementos que están en posición impar.
    - Los cuatro primeros elementos.
    - Los últimos tres elementos.
    - Los elementos entre el 4 y el 8 (incluido).

4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.

    - Todas las filas pares.

    - La primera columna y todas las filas.

5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".
    - Los valores de mi array bidimensional multiplicalos por el escalar 10.

6. Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:
    - Suma el primer array con el segundo.
    - Aplicar la potencia para el primer array elevado al segundo.

7. Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100
Calcula:

    - La media de los elementos
    - La media de las columnas y redondéalo a dos decimales
    - El valor máximo de cada fila
    - El valor mínimo de cada fila
    - Hay algun valor que sea mayor que 90 en tu array
    - Donde los podemos encontrar, cuáles son sus índices
    - Ordena el array de mayor a menor

📝 NOTA En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos.

In [1]:
### 7. 
import numpy as np

In [26]:
array = np.random.randint(0, 101, (2,3))

In [27]:
array

array([[92, 58,  6],
       [16, 23, 98]])

In [28]:
# La media de los elementos 
np.mean(array)

48.833333333333336

In [30]:
# La media de las columnas y redondéalo a dos decimales
np.mean(array, axis = 0)

array([54. , 40.5, 52. ])

In [31]:
# El valor máximo de cada fila
np.mean(array, axis = 1)

array([52.        , 45.66666667])

In [32]:
# El valor mínimo de cada fila
np.min(array, axis = 1)

array([ 6, 16])

In [39]:
# Hay algun valor que sea mayor que 90 en tu array
np.where(array > 90)

(array([0, 1], dtype=int64), array([0, 2], dtype=int64))

In [40]:
# Donde los podemos encontrar, cuáles son sus índices
np.ndim(array > 90)

2

In [41]:
# Ordena el array de mayor a menor
np.sort(array)

array([[ 6, 58, 92],
       [16, 23, 98]])